### ISSUE TITLE
gbfrelink.utility.manager1.0.4.7z shows virus detected unable to download

### ISSUE THREAD

**Issue by dogfishpaw** [WistfulHopes/gbfrelink.utility.manager#5]
gbfrelink.utility.manager1.0.4.7z shows virus detected unable to download
happens on Chrome and MS Edge.

**Comment by Nenkai** [comment]
This is unfortunately out of our control, antiviruses have been pretty picky on reloaded and certain mods.

**Comment by dogfishpaw** [comment]
Any way to download it? Browser automatically blocks it.
